name: sync PCL2Help

# Controls when the workflow will run
on:
  # push:
  schedule:
    - cron: '0 22 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  GET:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: clone repo
        run: |
          git clone https://github.com/LTCatt/PCL2Help.git
    
      - name: Run script
        run: |
          ls
          python sync.py
          
      - name: Commit changes
        run: |
          git config --local user.email "github-bot@example.com"
          git config --local user.name "Github-Bot"
          git add output/*
          git commit -m "Sync"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
